// Code generated by protoc-gen-go.
// source: dcache.proto
// DO NOT EDIT!

/*
Package get_info is a generated protocol buffer package.

It is generated from these files:
	dcache.proto

It has these top-level messages:
	Stat
	GetReq
	GetRes
	SetReq
	SetRes
	DelReq
	DelRes
	Address
	RegisterReq
	RegisterRes
	UnregisterReq
	UnregisterRes
	SyncRegistersReq
	SyncRegistersRes
	GetServStatusReq
	GetServStatusRes
*/
package get_info

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Statistics Data of key
type Stat struct {
	Rps float64 `protobuf:"fixed64,1,opt,name=rps" json:"rps,omitempty"`
}

func (m *Stat) Reset()                    { *m = Stat{} }
func (m *Stat) String() string            { return proto.CompactTextString(m) }
func (*Stat) ProtoMessage()               {}
func (*Stat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Stat) GetRps() float64 {
	if m != nil {
		return m.Rps
	}
	return 0
}

type GetReq struct {
	Group string `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	Key   string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
}

func (m *GetReq) Reset()                    { *m = GetReq{} }
func (m *GetReq) String() string            { return proto.CompactTextString(m) }
func (*GetReq) ProtoMessage()               {}
func (*GetReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetReq) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *GetReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetRes struct {
	Status bool   `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Value  []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Stat   *Stat  `protobuf:"bytes,3,opt,name=stat" json:"stat,omitempty"`
}

func (m *GetRes) Reset()                    { *m = GetRes{} }
func (m *GetRes) String() string            { return proto.CompactTextString(m) }
func (*GetRes) ProtoMessage()               {}
func (*GetRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetRes) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *GetRes) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *GetRes) GetStat() *Stat {
	if m != nil {
		return m.Stat
	}
	return nil
}

type SetReq struct {
	Group string `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	Key   string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *SetReq) Reset()                    { *m = SetReq{} }
func (m *SetReq) String() string            { return proto.CompactTextString(m) }
func (*SetReq) ProtoMessage()               {}
func (*SetReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SetReq) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *SetReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetReq) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SetRes struct {
	Status bool  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Stat   *Stat `protobuf:"bytes,2,opt,name=stat" json:"stat,omitempty"`
}

func (m *SetRes) Reset()                    { *m = SetRes{} }
func (m *SetRes) String() string            { return proto.CompactTextString(m) }
func (*SetRes) ProtoMessage()               {}
func (*SetRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SetRes) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *SetRes) GetStat() *Stat {
	if m != nil {
		return m.Stat
	}
	return nil
}

type DelReq struct {
	Group string `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	Key   string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
}

func (m *DelReq) Reset()                    { *m = DelReq{} }
func (m *DelReq) String() string            { return proto.CompactTextString(m) }
func (*DelReq) ProtoMessage()               {}
func (*DelReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DelReq) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *DelReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DelRes struct {
	Status bool   `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Value  []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Stat   *Stat  `protobuf:"bytes,3,opt,name=stat" json:"stat,omitempty"`
}

func (m *DelRes) Reset()                    { *m = DelRes{} }
func (m *DelRes) String() string            { return proto.CompactTextString(m) }
func (*DelRes) ProtoMessage()               {}
func (*DelRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DelRes) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *DelRes) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *DelRes) GetStat() *Stat {
	if m != nil {
		return m.Stat
	}
	return nil
}

type Address struct {
	Ip   string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Address) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Address) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type RegisterReq struct {
	Addr *Address `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
}

func (m *RegisterReq) Reset()                    { *m = RegisterReq{} }
func (m *RegisterReq) String() string            { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()               {}
func (*RegisterReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RegisterReq) GetAddr() *Address {
	if m != nil {
		return m.Addr
	}
	return nil
}

type RegisterRes struct {
	Status bool `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (m *RegisterRes) Reset()                    { *m = RegisterRes{} }
func (m *RegisterRes) String() string            { return proto.CompactTextString(m) }
func (*RegisterRes) ProtoMessage()               {}
func (*RegisterRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *RegisterRes) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type UnregisterReq struct {
	Addr *Address `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
}

func (m *UnregisterReq) Reset()                    { *m = UnregisterReq{} }
func (m *UnregisterReq) String() string            { return proto.CompactTextString(m) }
func (*UnregisterReq) ProtoMessage()               {}
func (*UnregisterReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *UnregisterReq) GetAddr() *Address {
	if m != nil {
		return m.Addr
	}
	return nil
}

type UnregisterRes struct {
	Status bool `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (m *UnregisterRes) Reset()                    { *m = UnregisterRes{} }
func (m *UnregisterRes) String() string            { return proto.CompactTextString(m) }
func (*UnregisterRes) ProtoMessage()               {}
func (*UnregisterRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *UnregisterRes) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type SyncRegistersReq struct {
	Addrs []*Address `protobuf:"bytes,1,rep,name=addrs" json:"addrs,omitempty"`
}

func (m *SyncRegistersReq) Reset()                    { *m = SyncRegistersReq{} }
func (m *SyncRegistersReq) String() string            { return proto.CompactTextString(m) }
func (*SyncRegistersReq) ProtoMessage()               {}
func (*SyncRegistersReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *SyncRegistersReq) GetAddrs() []*Address {
	if m != nil {
		return m.Addrs
	}
	return nil
}

type SyncRegistersRes struct {
	Status bool `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (m *SyncRegistersRes) Reset()                    { *m = SyncRegistersRes{} }
func (m *SyncRegistersRes) String() string            { return proto.CompactTextString(m) }
func (*SyncRegistersRes) ProtoMessage()               {}
func (*SyncRegistersRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *SyncRegistersRes) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type GetServStatusReq struct {
	Addr *Address `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
}

func (m *GetServStatusReq) Reset()                    { *m = GetServStatusReq{} }
func (m *GetServStatusReq) String() string            { return proto.CompactTextString(m) }
func (*GetServStatusReq) ProtoMessage()               {}
func (*GetServStatusReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *GetServStatusReq) GetAddr() *Address {
	if m != nil {
		return m.Addr
	}
	return nil
}

type GetServStatusRes struct {
	Status bool `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (m *GetServStatusRes) Reset()                    { *m = GetServStatusRes{} }
func (m *GetServStatusRes) String() string            { return proto.CompactTextString(m) }
func (*GetServStatusRes) ProtoMessage()               {}
func (*GetServStatusRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *GetServStatusRes) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*Stat)(nil), "get_info.Stat")
	proto.RegisterType((*GetReq)(nil), "get_info.GetReq")
	proto.RegisterType((*GetRes)(nil), "get_info.GetRes")
	proto.RegisterType((*SetReq)(nil), "get_info.SetReq")
	proto.RegisterType((*SetRes)(nil), "get_info.SetRes")
	proto.RegisterType((*DelReq)(nil), "get_info.DelReq")
	proto.RegisterType((*DelRes)(nil), "get_info.DelRes")
	proto.RegisterType((*Address)(nil), "get_info.Address")
	proto.RegisterType((*RegisterReq)(nil), "get_info.RegisterReq")
	proto.RegisterType((*RegisterRes)(nil), "get_info.RegisterRes")
	proto.RegisterType((*UnregisterReq)(nil), "get_info.UnregisterReq")
	proto.RegisterType((*UnregisterRes)(nil), "get_info.UnregisterRes")
	proto.RegisterType((*SyncRegistersReq)(nil), "get_info.SyncRegistersReq")
	proto.RegisterType((*SyncRegistersRes)(nil), "get_info.SyncRegistersRes")
	proto.RegisterType((*GetServStatusReq)(nil), "get_info.GetServStatusReq")
	proto.RegisterType((*GetServStatusRes)(nil), "get_info.GetServStatusRes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CacheServ service

type CacheServClient interface {
	Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetRes, error)
	Set(ctx context.Context, in *SetReq, opts ...grpc.CallOption) (*SetRes, error)
	Del(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*DelRes, error)
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterRes, error)
	Unregister(ctx context.Context, in *UnregisterReq, opts ...grpc.CallOption) (*UnregisterRes, error)
	SyncRegisters(ctx context.Context, in *SyncRegistersReq, opts ...grpc.CallOption) (*SyncRegistersRes, error)
	GetServStatus(ctx context.Context, in *GetServStatusReq, opts ...grpc.CallOption) (*GetServStatusRes, error)
}

type cacheServClient struct {
	cc *grpc.ClientConn
}

func NewCacheServClient(cc *grpc.ClientConn) CacheServClient {
	return &cacheServClient{cc}
}

func (c *cacheServClient) Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetRes, error) {
	out := new(GetRes)
	err := grpc.Invoke(ctx, "/get_info.CacheServ/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServClient) Set(ctx context.Context, in *SetReq, opts ...grpc.CallOption) (*SetRes, error) {
	out := new(SetRes)
	err := grpc.Invoke(ctx, "/get_info.CacheServ/Set", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServClient) Del(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*DelRes, error) {
	out := new(DelRes)
	err := grpc.Invoke(ctx, "/get_info.CacheServ/Del", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterRes, error) {
	out := new(RegisterRes)
	err := grpc.Invoke(ctx, "/get_info.CacheServ/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServClient) Unregister(ctx context.Context, in *UnregisterReq, opts ...grpc.CallOption) (*UnregisterRes, error) {
	out := new(UnregisterRes)
	err := grpc.Invoke(ctx, "/get_info.CacheServ/Unregister", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServClient) SyncRegisters(ctx context.Context, in *SyncRegistersReq, opts ...grpc.CallOption) (*SyncRegistersRes, error) {
	out := new(SyncRegistersRes)
	err := grpc.Invoke(ctx, "/get_info.CacheServ/SyncRegisters", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServClient) GetServStatus(ctx context.Context, in *GetServStatusReq, opts ...grpc.CallOption) (*GetServStatusRes, error) {
	out := new(GetServStatusRes)
	err := grpc.Invoke(ctx, "/get_info.CacheServ/GetServStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CacheServ service

type CacheServServer interface {
	Get(context.Context, *GetReq) (*GetRes, error)
	Set(context.Context, *SetReq) (*SetRes, error)
	Del(context.Context, *DelReq) (*DelRes, error)
	Register(context.Context, *RegisterReq) (*RegisterRes, error)
	Unregister(context.Context, *UnregisterReq) (*UnregisterRes, error)
	SyncRegisters(context.Context, *SyncRegistersReq) (*SyncRegistersRes, error)
	GetServStatus(context.Context, *GetServStatusReq) (*GetServStatusRes, error)
}

func RegisterCacheServServer(s *grpc.Server, srv CacheServServer) {
	s.RegisterService(&_CacheServ_serviceDesc, srv)
}

func _CacheServ_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/get_info.CacheServ/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServServer).Get(ctx, req.(*GetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheServ_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/get_info.CacheServ/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServServer).Set(ctx, req.(*SetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheServ_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/get_info.CacheServ/Del",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServServer).Del(ctx, req.(*DelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheServ_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/get_info.CacheServ/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheServ_Unregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServServer).Unregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/get_info.CacheServ/Unregister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServServer).Unregister(ctx, req.(*UnregisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheServ_SyncRegisters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRegistersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServServer).SyncRegisters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/get_info.CacheServ/SyncRegisters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServServer).SyncRegisters(ctx, req.(*SyncRegistersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheServ_GetServStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServServer).GetServStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/get_info.CacheServ/GetServStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServServer).GetServStatus(ctx, req.(*GetServStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _CacheServ_serviceDesc = grpc.ServiceDesc{
	ServiceName: "get_info.CacheServ",
	HandlerType: (*CacheServServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _CacheServ_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _CacheServ_Set_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _CacheServ_Del_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _CacheServ_Register_Handler,
		},
		{
			MethodName: "Unregister",
			Handler:    _CacheServ_Unregister_Handler,
		},
		{
			MethodName: "SyncRegisters",
			Handler:    _CacheServ_SyncRegisters_Handler,
		},
		{
			MethodName: "GetServStatus",
			Handler:    _CacheServ_GetServStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dcache.proto",
}

func init() { proto.RegisterFile("dcache.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x54, 0x5b, 0x8b, 0xd3, 0x40,
	0x14, 0xde, 0x5c, 0x1a, 0xbb, 0xa7, 0xbb, 0x4b, 0x1c, 0xbc, 0x84, 0x3c, 0x2d, 0x03, 0xcb, 0x2e,
	0x2b, 0x96, 0x52, 0x45, 0x50, 0x5f, 0x14, 0x8b, 0xc5, 0xd7, 0x19, 0x7c, 0xf1, 0x45, 0x62, 0x33,
	0xd6, 0x60, 0x69, 0xe2, 0xcc, 0xb4, 0xd0, 0x3f, 0xe4, 0xef, 0x94, 0x33, 0x49, 0xc8, 0xa5, 0x1d,
	0x21, 0x0f, 0xfb, 0x36, 0x33, 0xdf, 0xe5, 0x7c, 0x67, 0xce, 0x24, 0x70, 0x91, 0xae, 0x92, 0xd5,
	0x2f, 0x31, 0x2d, 0x64, 0xae, 0x73, 0x32, 0x5e, 0x0b, 0xfd, 0x3d, 0xdb, 0xfe, 0xcc, 0x69, 0x04,
	0x3e, 0xd7, 0x89, 0x26, 0x21, 0x78, 0xb2, 0x50, 0x91, 0x73, 0xed, 0xdc, 0x39, 0x0c, 0x97, 0x74,
	0x06, 0xc1, 0x52, 0x68, 0x26, 0xfe, 0x90, 0x27, 0x30, 0x5a, 0xcb, 0x7c, 0x57, 0x18, 0xf4, 0x9c,
	0x95, 0x1b, 0x54, 0xfc, 0x16, 0x87, 0xc8, 0x35, 0x67, 0xb8, 0xa4, 0xdf, 0x2a, 0x85, 0x22, 0xcf,
	0x20, 0x50, 0x3a, 0xd1, 0xbb, 0xd2, 0x70, 0xcc, 0xaa, 0x1d, 0x3a, 0xed, 0x93, 0xcd, 0x4e, 0x18,
	0xd5, 0x05, 0x2b, 0x37, 0x84, 0x82, 0x8f, 0x78, 0xe4, 0x5d, 0x3b, 0x77, 0x93, 0xf9, 0xd5, 0xb4,
	0x0e, 0x37, 0xc5, 0x64, 0xcc, 0x60, 0xf4, 0x33, 0x04, 0x7c, 0x50, 0x9a, 0xa6, 0x96, 0xd7, 0xaa,
	0x45, 0x17, 0x95, 0x8f, 0x3d, 0x63, 0x9d, 0xc6, 0xfd, 0x4f, 0x9a, 0x19, 0x04, 0x0b, 0xb1, 0x19,
	0x78, 0x37, 0x46, 0xf1, 0x10, 0x77, 0xf3, 0x12, 0x1e, 0x7d, 0x4c, 0x53, 0x29, 0x94, 0x22, 0x57,
	0xe0, 0x66, 0x75, 0x16, 0x37, 0x2b, 0x08, 0x01, 0xbf, 0xc8, 0x65, 0xd9, 0xcc, 0x88, 0x99, 0x35,
	0x7d, 0x0d, 0x13, 0x26, 0xd6, 0x99, 0xd2, 0x42, 0x62, 0x07, 0x37, 0xe0, 0x27, 0x69, 0x2a, 0x8d,
	0x68, 0x32, 0x7f, 0xdc, 0x54, 0xa8, 0x3c, 0x99, 0x81, 0xe9, 0x4d, 0x5b, 0x65, 0xed, 0x82, 0xbe,
	0x81, 0xcb, 0xaf, 0x5b, 0x39, 0xdc, 0xfe, 0xb6, 0xab, 0xb3, 0x17, 0x78, 0x0f, 0x21, 0x3f, 0x6c,
	0x57, 0x75, 0x16, 0x85, 0x35, 0x6e, 0x61, 0x84, 0x26, 0x48, 0xf5, 0x4e, 0x17, 0x29, 0x71, 0x7a,
	0x7f, 0x24, 0xb6, 0x17, 0x7a, 0x0b, 0xe1, 0x52, 0x68, 0x2e, 0xe4, 0x9e, 0x9b, 0x83, 0x01, 0xcd,
	0xdc, 0x1f, 0x49, 0xad, 0x65, 0xe6, 0x7f, 0x3d, 0x38, 0xff, 0x84, 0x9f, 0x26, 0xd2, 0xc9, 0x0b,
	0xf0, 0x96, 0x42, 0x93, 0xb0, 0x71, 0x2e, 0xbf, 0xc1, 0xb8, 0x7f, 0xa2, 0xe8, 0x19, 0x92, 0x79,
	0x97, 0xcc, 0x8f, 0xc8, 0xbc, 0x45, 0x5e, 0x88, 0x4d, 0x9b, 0x5c, 0xbe, 0xe0, 0xb8, 0x7f, 0x82,
	0xe4, 0x77, 0x30, 0xae, 0xef, 0x88, 0x3c, 0x6d, 0xf0, 0xd6, 0xb3, 0x89, 0x4f, 0x1e, 0xa3, 0xf6,
	0x03, 0x40, 0x33, 0x49, 0xf2, 0xbc, 0xa1, 0x75, 0xde, 0x45, 0x6c, 0x01, 0xd0, 0xe1, 0x0b, 0x5c,
	0x76, 0xa6, 0x44, 0xe2, 0x56, 0x3f, 0xbd, 0xd9, 0xc7, 0x76, 0xac, 0xb2, 0xea, 0x4c, 0xa2, 0x6d,
	0xd5, 0x9f, 0x6e, 0x6c, 0xc7, 0x14, 0x3d, 0xfb, 0x11, 0x98, 0x5f, 0xe7, 0xab, 0x7f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x0e, 0x96, 0xf8, 0x89, 0x4a, 0x05, 0x00, 0x00,
}
